#!/bin/bash

# Script to add user configs to the i3 configs 

i3File=/home/cookinduck/.config/i3/config

if grep -q "USER CONFIGS" $i3File; then 
	echo "" 
	echo "I3 user configurations already added. See /"$i3File/" for more details (Aborting)." 
	echo "" 
else
	echo "" >> $i3File
	echo "#USER CONFIGS" >> $i3File
	echo "" >> $i3File
	echo "" >> $i3File
	echo "#bindsym \$mod+Return exec alacritty" >> $i3File
	echo "" >> $i3File
	echo "# split in horizontal orientation (vim) " >> $i3File
	echo "#bindsym \$mod+i split h" >> $i3File
	echo "" >> $i3File
	echo "# change focus (vim)" >> $i3File
	echo "#bindsym \$mod+h focus left" >> $i3File
	echo "#bindsym \$mod+j focus down" >> $i3File
	echo "#bindsym \$mod+k focus up" >> $i3File
	echo "#bindsym \$mod+l focus right" >> $i3File
	echo "" >> $i3File
	echo "# move focused window (vim)" >> $i3File
	echo "#bindsym \$mod+Shift+h move left" >> $i3File
	echo "#bindsym \$mod+Shift+j move down" >> $i3File
	echo "#bindsym \$mod+Shift+k move up" >> $i3File
	echo "#bindsym \$mod+Shift+l move right" >> $i3File
	echo "" >> $i3File
	echo "# kill focused window (easy)" >> $i3File
	echo "#bindsym \$mod+q kill" >> $i3File
	echo "" >> $i3File
	echo "exec_always --no-startup-id /usr/local/bin/seasonalwallpaper" >> $i3File
	echo "" >> $i3File
	echo "# start rofi (a program launcher)" >> $i3File
	echo "#bindsym \$mod+d exec --no-startup-id \"rofi -show drun\"" >> $i3File
fi
