#!/bin/bash

# Script to configure poly bar for custom settings

# Creates a new config file for polybar
mkdir -p /home/cookinduck/.config/polybar

# Copies original config file to user config location
polybarConfig=/etc/polybar/config.ini
origConfig=/usr/local/bin/original-configs/polybar/config.ini.orig
i3Config=/home/cookinduck/.config/i3/config

# Replaces current polybar config with original
 cat $origConfig > $polybarConfig

# Changes "example" to "bar1" to allow polybar to launch correct bar
sed -i 's/example/bar1/' "$polybarConfig"

# Adds suggested line and comments out current bar in i3 config file
if grep -q "polybar" $i3Config; then 
	echo ""
	echo "I3 config already configured with polybar, see \"$i3Config\" for details (Aborting)."
	echo ""
else
	echo "" >> "$i3Config"
	echo "exec_always --no-startup-id /home/cookinduck/.config/polybar/launch.sh" >> "$i3Config"
	sed -i '193,206s/^/#/' "$i3Config"
	echo ""
	echo "Polybar configred in i3 config."
	echo ""
fi

# Adds launch script to config file is missing
launchPath=/home/cookinduck/.config/polybar
launchSize=$(ls -ltr $launchPath | wc -l)
if (( launchSize == 1 )); then 
	touch $launchPath/launch.sh
	echo "#!/bin/bash" >> $launchPath/launch.sh 
	echo "" >> $launchPath/launch.sh 
	echo "# Terminate already running bar instance." >> $launchPath/launch.sh
	echo "polybar-msg cmd quit" >> $launchPath/launch.sh 
	echo "" >> $launchPath/launch.sh 
	echo "# Launch bar1" >> $launchPath/launch.sh 
	echo "echo \"---\" | tee -a /tmp/polybar1.log" >> $launchPath/launch.sh 
	echo "polybar bar1 2>&1 | tee -a /tmp/polybar1.log & disown" >> $launchPath/launch.sh 
	echo "echo \"Polybar launched.\"" >> $launchPath/launch.sh 
	chmod 755 $launchPath/launch.sh
fi
	

# Makes adjustements to polybar config file
sed -i 's/height = 27pt/height = 22pt/' $polybarConfig
sed -i 's/background = #282A2E/background = #32323f/' $polybarConfig
sed -i 's/background-alt = #373B41/background-alt = #48485f/' $polybarConfig
sed -i 's/foreground = #C5C8C6/foreground = #dfdfdf/' $polybarConfig
sed -i 's/primary = #F0C674/primary = #8790b4/' $polybarConfig
sed -i 's/secondary = #8ABEB7/secondary = #90fffc/' $polybarConfig
sed -i 's/alert = #A54242/alert = #f3407a/' $polybarConfig
sed -i 's/disabled = #707880/disabled = #8ca7b8/' $polybarConfig
sed -i 's/radius = 6/radius = 9/' $polybarConfig
sed -i 's/line-size = 3pt/line-size = 0pt/' $polybarConfig
sed -i 's/module-margin = 1/module-margin = 2/' $polybarConfig
sed -i 's/separator = |/separator =/' $polybarConfig
sed -i 's/modules-right = filesystem pulseaudio xkeyboard memory cpu wlan eth date/modules-right = memory cpu wlan eth battery/' $polybarConfig
sed -i 's/modules-left = xworkspaces xwindow/modules-left = xworkspaces xwindow filesystem/' $polybarConfig
sed -i "s/modules-right = memory cpu wlan eth battery/modules-right = memory cpu wlan eth battery\nmodules-center = date/" $polybarConfig
sed -i 's/F0C674/8790b4/' $polybarConfig
sed -i 's/%local_ip%//' $polybarConfig
sed -i 's/date = %H:%M/date = %m-%d-%y    %H:%M:%S/' $polybarConfig
sed -i 's/label-foreground = ${colors.primary}/label-foreground = ${colors.foreground}/' $polybarConfig;
sed -i '103,125s/^/;/' $polybarConfig
sed -i "s/label-empty-padding = 1/label-empty-padding = 1\n\n[module\/battery]\ntype = internal\/battery\nfull-at = 99\nlow-at = 5\nbattery = BAT1\napapter = ACAD\npoll-interval = 5/" $polybarConfig

echo "Polybar fully configured. Restart system to see changes."
echo ""
