#!/bin/bash

# bash script to configure lightdm.

configFile=/etc/lightdm/slick-greeter.conf
picturePath=/home/cookinduck/Pictures
if ls -ltr $picturePath | grep -q loginPicture ;then 
	echo ""
	echo "Login picture directory found. Continuing config..."
	echo ""
else
	echo ""
	echo "Making login picture directory..."
	echo ""
	(cd $picturePath; mkdir loginPicture)
fi

if ls -ltr $picturePath/loginPicture | grep -q picture ;then
	echo "Picture \"picture\" found. Continuing config..."
	echo ""
else 
	echo "Picture \"picture\" not found. Grabbing default picture..."
	echo ""
	echo "NOTE: If you have a picture, ensure it is named \"picture\". Continuing config..."
	echo ""
	wget https://i.imgur.com/E7ymJ5Y.png -P $picturePath/loginPicture
	(cd $picturePath/loginPicture; mv * /home/cookinduck/Pictures/loginPicture/picture)
fi

echo "Setting login picture..."
echo ""
chmod 777 $picturePath/loginPicture/picture
cp $picturePath/loginPicture/picture /usr/share/backgrounds/f37/default/f37-01-day.png
