#!/bin/bash

# Root script to install essential packages.

echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Updating and upgrading DNF Repository...                                 #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""

# Removes mousepad
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Uninstalls Mousepad...                                                   #" 
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf remove -y mousepad

# Removes azote 
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Uninstalls Azote (Wallpaper manager)...                                  #" 
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf remove -y azote

# Removes disks
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Uninstalls Disks...                                                      #" 
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf remove -y gnome-disk-utility

# Installs i3gaps.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing i3 gaps and removing i3...                                    #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf remove -y i3
dnf copr -y enable fuhrmann/i3-gaps
dnf install -y i3-gaps

# Updates and upgrade repo
dnf update -y && dnf upgrade -y

# Installs the one true editor v2.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing vim...                                                        #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y vim 

# Installs the one true editor v3.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing neovim...                                                     #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y neovim python3-neovim 

# Installs Alacritty terminal emulator.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing alacritty terminal emulator with dependencies...              #"
echo "#                                                                             #"

echo "###############################################################################"
echo ""
dnf install -y cmake freetype-devel fontconfig-devel libxcb-devel libxkbcommon-devel g++
dnf group install -y "Development Tools"
dnf install -y alacritty

# Installs polybar Status bar.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing polybar Status Bar...                                         #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y  polybar

# Installs Rofi window switcher.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing Rofi...                                                       #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y rofi

# Installs picom and depencendies.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing picom with dependencies...                                    #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y dbus-devel gcc git libconfig-devel libdrm-devel 
dnf install -y libev-devel libX11-devel libX11-xcb libXext-devel
dnf install -y libxcb-devel libGL-devel libEGL-devel meson
dnf install -y pcre2-devel pixman-devel uthash-devel 
dnf install -y xcb-util-image-devel xcb-util-renderutil-devel xorg-x11-proto-devel
dnf install -y xcb-util-xrm-devel
python3 -m pip install asciidoc

echo "Making directory for cloned git repos..."
mkdir /home/cookinduck/git
(cd /home/cookinduck/git; git clone https://github.com/yshui/picom; cd /home/cookinduck/git/picom; git submodule update --init --recursive; meson setup --buildtype=release . build; ninja -C build; ninja -C build install)

# Installs inxi.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing inxi...                                                       #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y inxi

# Installs flameshot.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing flameshot...                                                  #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y flameshot

# Installs scrot.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing scrot...                                                      #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y scrot

# Installs openVPN.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing openVPN...                                                    #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y openvpn

# Installs openSSL.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing openSSL...                                                    #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y openssl

# Installs openresolv.
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing openresolv...                                                 #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y openresolv

# Installs libnsl
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing libnsl/libnsl2...                                             #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y libnsl
dnf install -y libnsl2-devel

# Installs RPM Fusion
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing RPM Fusion repository...                                      #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Installs Flatpack
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installing Flatpack...                                                   #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Installs Discord
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installs Discord (from dnf)...                                        #"
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf update
dnf install -y discord

# Installs ranger File Manager
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installs ranger File Manager...                                            #" 
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf remove -y thunar
if ls -ltr /home/cookinduck/.config | grep -q "Thunar" ; then
	rm -rf /home/cookinduck/.config/Thunar
fi
dnf install -y ranger

# Installs neofetch 
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installs neofetch...                                                     #" 
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y neofetch

# Installs node
echo ""
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installs Node.js...                                                      #" 
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y nodejs

# Installs xsel 
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installs xsel...                                                         #" 
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y xsel

# Installs ripgrep
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installs ripgrep...                                                      #" 
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y ripgrep

# Installs pip3 
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installs pip3...                                                         #" 
echo "#                                                                             #"
echo "###############################################################################"
echo ""
dnf install -y python3-pip

# Installs neovim support packages
echo "###############################################################################"
echo "#                                                                             #"
echo "#    Installs nvim support (python / node)...                                 #" 
echo "#                                                                             #"
echo "###############################################################################"
echo ""
pip install pynvim
npm i -g neovim

