#!/bin/bash

# A script to do basic security measure on system startup.

# Ensure firewalld is enabled and started
echo ""
echo "Ensuring firewall is started and enabled..."
echo ""
systemctl enable firewalld
systemctl start firewalld

